### ISSUE TITLE
Bro

### ISSUE THREAD

**Issue by PeterDavidCarter** [stereobooster/dev.wtf#4]
Do you even code?

**Comment by stereobooster** [comment]
<img width="1265" alt="Screenshot 2019-09-23 at 23 49 11" src="https://user-images.githubusercontent.com/179534/65465538-dbf2f100-de5c-11e9-9938-7ca323b71682.png">
<img width="1262" alt="Screenshot 2019-09-23 at 23 49 37" src="https://user-images.githubusercontent.com/179534/65465540-dc8b8780-de5c-11e9-9739-d0fa3b4de59f.png">
